# Generated by Django 4.2.6 on 2023-11-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('codice_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='esame',
            name='paziente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionale.paziente'),
        ),
    ]
